# Generated by Django 4.1.7 on 2023-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('idattestation', models.AutoField(primary_key=True, serialize=False)),
                ('attestation', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'attestation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attestationrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attestationrequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('idbac', models.AutoField(db_column='idBAC', primary_key=True, serialize=False)),
                ('bac', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('idfiliere', models.AutoField(db_column='idFiliere', primary_key=True, serialize=False)),
                ('nomfiliere', models.CharField(blank=True, db_column='nomFiliere', max_length=45, null=True)),
                ('intitulefiliere', models.CharField(blank=True, db_column='intituleFiliere', max_length=45, null=True)),
            ],
            options={
                'db_table': 'filiere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('idhandicap', models.AutoField(db_column='idHandicap', primary_key=True, serialize=False)),
                ('handicap', models.CharField(blank=True, db_column='Handicap', max_length=45, null=True)),
            ],
            options={
                'db_table': 'handicap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('idmention', models.AutoField(primary_key=True, serialize=False)),
                ('mention', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'module',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idprofile', models.AutoField(db_column='idProfile', primary_key=True, serialize=False)),
                ('cne', models.CharField(blank=True, db_column='CNE', max_length=45, null=True)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('prenom', models.CharField(blank=True, max_length=45, null=True)),
                ('cin', models.CharField(blank=True, db_column='CIN', max_length=45, null=True)),
                ('datenaissance', models.CharField(blank=True, db_column='dateNaissance', max_length=45, null=True)),
                ('lieunaissance', models.CharField(blank=True, db_column='lieuNaissance', max_length=45, null=True)),
                ('profileimg', models.ImageField(default='media/blank-profile-picture.png', upload_to='profile_images')),
                ('tel', models.IntegerField(blank=True, db_column='Tel', null=True)),
                ('obtionbac', models.CharField(blank=True, max_length=45, null=True)),
                ('mail', models.CharField(blank=True, max_length=45, null=True)),
                ('mailacademique', models.CharField(blank=True, max_length=45, null=True)),
                ('arabicnam', models.CharField(blank=True, max_length=45, null=True)),
                ('arabiclieunaissance', models.CharField(blank=True, max_length=45, null=True)),
                ('pays', models.CharField(blank=True, db_column='Pays', max_length=45, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=100, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idsemestre', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('idsex', models.AutoField(db_column='idSEX', primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=45, null=True)),
            ],
            options={
                'db_table': 'sex',
                'managed': False,
            },
        ),
    ]
