# Generated by Django 4.1.7 on 2023-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cne',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
