# Generated by Django 4.1.7 on 2023-03-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_cne'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_cin', to='app.profile')),
                ('cne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_cne', to='app.profile')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_nom', to='app.profile')),
                ('prenom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_prenom', to='app.profile')),
            ],
        ),
    ]
