# Generated by Django 4.1.7 on 2023-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attestation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='cin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='cne',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
