# Generated by Django 4.1.7 on 2023-03-18 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attestation_cin_alter_attestation_cne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='cne',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='attestation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='app.profile'),
        ),
    ]
