# Generated by Django 4.1.7 on 2023-03-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_attestation_profile_attestation_cin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attestation',
        ),
    ]
